// Test para verificar que el código compila correctamente
import type { MatriculaLocal } from "./src/api/types";
import { ESTADO_ASIGNATURA } from "./src/api/types";
import { verificarAsignaturasMatriculas, formatearReporteAsignaturas } from "./src/utils/verificarAsignaturas";

// Datos de prueba
const matriculas: MatriculaLocal[] = [
  {
    localId: "local-1",
    rowId: "row-1",
    origenRowId: "origen-1",
    nOrden: 1,
    nombreMatricula: "Matricula 1",
    nombre: "Juan",
    apellidos: "Pérez",
    dni: "12345678A",
    email: "juan@example.com",
    telefono: null,
    fechaNacimiento: null,
    domicilio: null,
    localidad: null,
    provincia: null,
    cp: null,
    fechaInscripcion: "2026-01-01",
    createdon: "2026-01-01",
    cursoEscolar: "2025-2026",
    ensenanzaCurso: "EP1",
    especialidad: "Canto",
    formaPago: null,
    reduccionTasas: null,
    autorizacionImagen: false,
    disponibilidadManana: false,
    horaSalida: null,
    docFaltante: null,
    repetidor: false,
    asignaturas: [
      {
        localId: "asig-1",
        rowId: "asig-row-1",
        asignaturaId: "asig-uuid-1",
        codigo: 1001,
        nombre: "Lenguaje Musical",
        estado: ESTADO_ASIGNATURA.MATRICULADA,
        observaciones: null,
        horario: null,
      },
      {
        localId: "asig-2",
        rowId: "asig-row-2",
        asignaturaId: "asig-uuid-2",
        codigo: 1002,
        nombre: "Técnica de la Voz",
        estado: ESTADO_ASIGNATURA.MATRICULADA,
        observaciones: null,
        horario: null,
      },
    ],
    anulacion: false,
    ampliacion: false,
    ampliada: false,
    esTemporal: false,
    sustituyeATemporalId: "temp-1",
    _pendienteSubida: false,
    _guardadoEn: "2026-01-01",
    _modificadoEn: "2026-01-01",
    _tienePdf: false,
  },
  {
    localId: "temp-1",
    rowId: null,
    origenRowId: "temp-origen-1",
    nOrden: null,
    nombreMatricula: "Temporal 1",
    nombre: "Juan_Temp",
    apellidos: "Pérez_Temp",
    dni: "",
    email: "",
    telefono: null,
    fechaNacimiento: null,
    domicilio: null,
    localidad: null,
    provincia: null,
    cp: null,
    fechaInscripcion: "2026-01-01",
    createdon: "2026-01-01",
    cursoEscolar: "2025-2026",
    ensenanzaCurso: "EP1",
    especialidad: "Canto",
    formaPago: null,
    reduccionTasas: null,
    autorizacionImagen: false,
    disponibilidadManana: false,
    horaSalida: null,
    docFaltante: null,
    repetidor: false,
    asignaturas: [
      {
        localId: "asig-temp-1",
        rowId: null,
        asignaturaId: null,
        codigo: 0,
        nombre: "Lenguaje Musical",
        estado: ESTADO_ASIGNATURA.MATRICULADA,
        observaciones: null,
        horario: null,
      },
      // Falta "Técnica de la Voz" - incoherencia
    ],
    anulacion: false,
    ampliacion: false,
    ampliada: false,
    esTemporal: true,
    temporalNumero: 1,
    temporalEstado: "vinculado",
    sustituidoPorLocalId: null,
    _pendienteSubida: false,
    _guardadoEn: "2026-01-01",
    _modificadoEn: "2026-01-01",
    _tienePdf: false,
  },
];

console.log("Ejecutando verificación...");
const reporte = verificarAsignaturasMatriculas(matriculas, "EP1");
console.log("\nReporte:");
console.log(JSON.stringify(reporte, null, 2));

console.log("\n" + formatearReporteAsignaturas(reporte));
